nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: []
        allow_headers: []
        allow_methods: []
        expose_headers: []
        max_age: 0
        hosts: []
        origin_regex: false
        forced_allow_origin_value: ~
        skip_same_as_origin: true
    paths:
        '^/api/':
            allow_credentials: true
            allow_origin: ['https://space-echoes.surge.sh', 'https://spaceechoes.vercel.app']
            allow_headers: ['Content-Type', 'Authorization', 'Access-Control-Allow-Origin']
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
            expose_headers: ['Link', 'Location']

